CREATE TABLE user_social_links (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT,
    platform VARCHAR(50),
    url VARCHAR(255),
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    FOREIGN KEY (user_id) REFERENCES users(id)
);